import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import styles from "./layout.module.css"
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Fooret";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Lepestki",
	description: "Generated by create next app",
	keywords: "flowers"
};

const MainLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang="en">

			<Navbar />
			<main className={inter.className}>{children}</main>
			<Footer />

		</html>
	);
}

export default MainLayout